name: Integrity check

on:
  pull_request:
  push:

jobs:
  code_style:
    runs-on: ubuntu-latest
    name: Code style check
    steps:
      - name: Git clone
        uses: actions/checkout@master

      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.4
          coverage: pcov

      - name: Install composer dependencies
        run: |
          composer run cs:install

          # Install app dependencies
          composer install --no-interaction --prefer-dist

      # Check code checker and coding standards
      - name: Check coding standards
        run: |
          composer run cs:check

      - name: Check PHPStan rules
        run: vendor/bin/phpstan analyse src -c phpstan.neon --level 8 --no-progress

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.2', '7.3', '7.4'] # 8.0

    name: PHP ${{ matrix.php }} tests
    steps:
      - name: Git clone
        uses: actions/checkout@master

      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov

      - name: Install composer dependencies
        run: |
          composer install --no-interaction --prefer-dist

      - name: Run tests
        run: composer run test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
